openapi: 3.0.1
info:
  title: PacaPitch
  description: API for PacePitch media server
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /create/session:
    post:
      summary: Create a new pitching session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePitchingSessionRequest'
      responses:
        '200':
          description: Successfully created a pitching session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PitchingSessionEntity'

  /session/{sessionId}/upload/video:
    post:
      summary: Upload a video file
      description: Upload a video file to MinIO and save the URL in the database
      parameters:
        - $ref: '#/components/parameters/sessionIdPathParam'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The video file to upload
      responses:
        '200':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: string
        '500':
          description: File upload failed
          content:
            application/json:
              schema:
                type: string

  /session/{videoId}/upload/info:
    post:
      summary: Update video information
      parameters:
        - $ref: '#/components/parameters/videoIdPathParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateVideoInfoRequest'
      responses:
        '200':
          description: Video information updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndividualPitchEntity'
  /session/{sessionId}/upload/thumb:
    get:
      summary: Get the oldes thumbnail URL and session title
      parameters:
        - in: path
          name: sessionId
          required: true
          schema:
            type: string
            format: uuid
          description: The ID of the session
      responses:
        '200':
          description: The oldest thumbnail URL and session title
          content:
            application/json:
              schema:
                type: object
                properties:
                  thumbnailUrl:
                    type: string
                    example: "https://example.com/thumbnail.png"
                  sessionTitle:
                    type: string
                    example: "Session Title"
        '500':
          description: Failed to retrieve thumbnail URL and session title
          content:
            text/plain:
              schema:
                type: string
                example: "Failed to retrieve thumbnail URL and session title: error message"
  /session/upload/thumb/{videoId}:
    get:
      summary: Get the thumbnail URL and memo for a specific video
      parameters:
        - in: path
          name: videoId
          required: true
          schema:
            type: string
            format: uuid
          description: The ID of the video
      responses:
        '200':
          description: The thumbnail URL and memo for the video
          content:
            application/json:
              schema:
                type: object
                properties:
                  thumbnailUrl:
                    type: string
                    example: "https://example.com/thumbnail.png"
                  memo:
                    type: string
                    example: "This is a memo"
        '500':
          description: Failed to retrieve thumbnail URL and memo
          content:
            text/plain:
              schema:
                type: string
                example: "Failed to retrieve thumbnail URL and memo: error message"
  /session/upload/video/{videoId}:
    get:
      summary: Get the video URL for a specific video
      parameters:
        - in: path
          name: videoId
          required: true
          schema:
            type: string
            format: uuid
          description: The ID of the video
      responses:
        '200':
          description: The video URL
          content:
            text/plain:
              schema:
                type: string
                example: "https://example.com/video.mp4"
        '500':
          description: Failed to retrieve video URL
          content:
            text/plain:
              schema:
                type: string
                example: "Failed to retrieve video URL: error message"


components:
  schemas:
    CreatePitchingSessionRequest:
      type: object
      properties:
        title:
          type: string
        memo:
          type: string
      required:
        - title

    PitchingSessionEntity:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        memo:
          type: string
        createdAt:
          type: integer
          format: int64
        updatedAt:
          type: integer
          format: int64
      required:
        - title

    CreateVideoInfoRequest:
      type: object
      properties:
        velocity:
          type: number
          format: double
        pitchType:
          type: string
        memo:
          type: string
        throwingHand:
          type: string

    IndividualPitchEntity:
      type: object
      properties:
        id:
          type: string
          format: uuid
        session:
          $ref: '#/components/schemas/PitchingSessionEntity'
        velocity:
          type: number
          format: double
        pitchType:
          type: string
        memo:
          type: string
        throwingHand:
          type: string
        createdAt:
          type: integer
          format: int64
        updatedAt:
          type: integer
          format: int64
        minioObjectName:
          type: string
        minioUrl:
          type: string

  parameters:
    videoIdPathParam:
      name: videoId
      in: path
      required: true
      description: The UUID of the video (primary key of 'individual_pitches' table)
      schema:
        type: string
        format: uuid

    sessionIdPathParam:
      name: sessionId
      in: path
      required: true
      description: The ID of the session
      schema:
        type: string
        format: uuid





